---
- name: Prepare the server and client
  gather_facts: yes
  become: yes
  hosts: all

  tasks:
  - name: Connection test
    ping:
  - name: Make sure pip3 installed
    become: true
    apt:
      name:
        - python3-pip
      state: present
# Make sure the directory exist
  - name: Creates directory
    file:
      path: /opt/monitoring
      state: directory
#Copy the script to the remote server.
  - copy:
      src: server/app.py
      dest: /opt/monitoring/app.py
      mode: u+x
#Install prerequisite
- name: Install server prerequisite
  gather_facts: yes
  hosts: server
  tasks:
  - pip:
      name:
        - Flask==2.0.3
        - Flask-SocketIO==5.1.1
        - requests==2.18.4
      executable: pip3 
  - name: execute the script
    shell: nohup python3 app.py &
    args:
      chdir: /opt/monitoring
- name: Install client prerequisite
  gather_facts: yes
  hosts: client
  tasks:
  - pip:
      name:
        - watchdog==2.1.6
        - requests==2.18.4
      executable: pip3 
  - name: execute the script
    shell: nohup python3 app.py &
    args:
      chdir: /opt/monitoring